### ISSUE TITLE
PDF: bundle libraries?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/print#13]
Can we bundle PDF libraries in the related submodules? Or make wrapper modules for these libraries and add as dependencies?

 - wkhtmltopdf: https://github.com/wkhtmltopdf/wkhtmltopdf LGPL-3.0
 - mpdf: https://github.com/mpdf/mpdf GPL-2.0
 - dompdf: https://github.com/dompdf/dompdf LGPL-2.1
 - tcpdf: https://sourceforge.net/projects/tcpdf/files/ LGPL-3.0

**Comment by laryn** [comment]
RE: Licensing between GPL and LGPL, [see here](https://softwareengineering.stackexchange.com/a/342158/155167). And further in the comments some simplified math for people like me: `LGPL + GPL → GPL` but  `LGPL-3.0 + GPL-2.0-or-later → GPL-3.0-or-later`.

**Comment by bugfolder** [comment]
[TCPDF is now a Backdrop module.](https://backdropcms.org/project/tcpdf)

**Comment by argiepiano** [comment]
But it seems like print can't see the TCPDF library wrapped by that module? https://forum.backdropcms.org/forum/tcpdf 

After enabling the TCPDF wrapper, and this module's:
- PDF version
- Printer-friendly pages
- Printer-friendly pages UI
- TCPDF library handler

The site still says "No PDF generation tool found! Please download a supported PHP PDF generation tool. Check this module's INSTALL.txt for more details."

**Comment by bugfolder** [comment]
The [Webform2PDF module](https://backdropcms.org/project/webform2pdf) uses [TCPDF module](https://backdropcms.org/projecct/tcpdf) to create its PDFs; maybe look at that module to see how to include the  library in another module.

**Comment by laryn** [comment]
There is likely some integration work needed to find the new wrapper module and use that library, but I doubt it would take too much effort.

**Comment by argiepiano** [comment]
Yes, the integration is pretty simple, but there are some issues with all the pdf related functions, mostly product of coder_upgrade. See for example [this line](https://github.com/backdrop-contrib/print/blob/93d89a9401c673485b7d5c9a5984d1e752a5a7c1/print_pdf/lib_handlers/print_pdf_tcpdf/print_pdf_tcpdf.pages.inc#L67) (!!!)

**Comment by argiepiano** [comment]
@laryn, PR provided. 

There were some confusing handlings of config files (originally handled by variables in D7). This affected the display of the PDF version link. In D7, the text for the link was stored in a variable such as `print_html_link_text` and `print_pdf_link_text`. In Backdrop, previous work moved the value of the HTML printer friendly version text into config `print.settings`. The problem is that the text for PDF version is being stored in `print_pdf.settings`. So, I had to insert an if statement to find it in the correct location. Otherwise, the other option might be to store the HTML text in `print_html.settings`, but that would required lots of changes, plus an upgrade hook, since it would need to change existing installations.

**Comment by laryn** [comment]
Thanks @argiepiano for that PR, I had a chance to test it today and it's a big improvement. Thanks @bugfolder for the wrapper module!

**Comment by laryn** [comment]
I don't actually have a site that's using this module currently, but I think merging your improvement and leaving further cleanup to config files as a sometime-future project makes sense.
