### ISSUE TITLE
Not working with mpdf (libary is not loaded?)

### ISSUE THREAD

**Issue by hoorack** [backdrop-contrib/print#33]
After fresh install of recommended version of the module (1.x-2.4.0-beta5), mpdf library (many versions tried, the older fails on compatibility issue with new PHP) with PHP 8.2 and Backdrop 1.29.0 - although the library seems to be loaded on module configuration page, pdf is not being generated and any /printpdf page exits with error: `syntax error, unexpected identifier "Mpdf"`
All directory permissions are set correctly in the library dir.
Is there anything I am doing wrong? Are there any recommendations about mpdf versions and/or location of it? Thanks!

**Comment by argiepiano** [comment]
Print is a buggy module, but I've succeeded in using mpdf.  This has worked for me so far - it's an imperfect solution as it will potentially interfere with other libraries:

1. Use composer to install the current version (8.1.0). You have to do this from the command line. Go to the root of your installation and run `composer require mpdf/mpdf`
2. This will create a  folder called `vendor`
3. Create a `libraries` module on the root of your Backdrop installation
4. Create a subfolder called `mpdf` inside that
5. Move the `vendor` folder into `libraries/mpdf/`
6. Then navigate to `admin/config/user-interface/print/pdf` to be sure that the library is now found
7. You will also need to enable the pdf print links to be shown everywhere etc in `admin/config/user-interface/print/ui`
8. There seems to be a bug that prevents the link to have any text - but if you inspect the page for a node with your browser, for example you'll see the link that looks like `printpdf/1` to send node id 1 to mpdf

One more step. There is a bug that seems the result of the maintainer using `coder_upgrade` to upgrade this module. Open `print_pdf_mpdf.pages.inc` and edit line 66 to show `    $mpdf = new \Mpdf\Mpdf($config);`

Currently the back slashes are both missing.

Then navigate to a node page and manually type `example.com/printpdf/NID` (replace NID with the node id)

Unfortunately `print` hardcodes the locations of the libraries in `_print_scan_libs()`. I would suggest to the maintainer that, given the current state of `mpdf` (you MUST use composer) it'd be wise to either include a version of the mpdf library wrapped in the module, or to assume that we are using modern libraries and to look for the library autoloader in `vendor` instead of within `libraries/mpdf`.

**Comment by hoorack** [comment]
Thank you for your help! In fact, I did not have problem with issues you numbered 1-8, but the _really_ headache were the missing backslashes on the line 66 of print_pdf_mpdf.pages.inc. That syntax was correct for ancient versions of mpdf ( < 7 ). Maybe it would be great if the module detects the version of the library and adjusts the library call due to the library version.

**Comment by argiepiano** [comment]
I'm reopening this since this bug (missing slashes) needs to b fixed.

**Comment by argiepiano** [comment]
In fact it does detect version 7 and above. This was a simple syntax error. The reason why  it worked with versions smaller than 7 is because of the if statement:

```php
  // Set document information.
  if ($mpdf_version_7_plus) {
    $config['mode'] = 'utf-8';
    $config['format'] = $format;
    $mpdf = new \Mpdf\Mpdf($config);
  }
  else {
    $mpdf = new mPDF('UTF-8', $format);
  }
```

**Comment by laryn** [comment]
Fixed the typo and filed a followup (here, in case you want to discuss further: https://github.com/backdrop-contrib/print/issues/35)

Thanks to you both!
